### ISSUE TITLE
Piece of ring shape in openlayers "removeArc()" function

### ISSUE THREAD

**Issue by savasturk** [mikopos/ArcLib#2]
How can we use the removeArc() function properly?

**Comment by mikopos** [comment]
What exactly do you mean properly? If you call removeArc() from an event in javascript and provide it with a source vector and the features you want to remove from vector, it will do its job. Have you tried something and it does not work ?

**Comment by savasturk** [comment]
![shape](https://user-images.githubusercontent.com/23220290/69224307-5b671d00-0b8d-11ea-9351-ae5adcdb15e9.png)


I want to produce this shape, how can I produce this shape with removeArc() function?

**Comment by mikopos** [comment]
Actually what you request could be an enhancement to the library, since at this time, is capable of constructing more simple arcs. This structure requires multiple styles, which are not supported by the time being, but I keep your request in mind for near time enhancement.

**Comment by savasturk** [comment]
Thank you, I added this structure with the createArcwithDirectionInDegrees() function. I will share in there.

[createArc.txt](https://github.com/mikopos/ArcLib/files/3872917/createArc.txt)
